# Managed by Ansible "baseline" role

# Baseline
PermitRootLogin no
PasswordAuthentication no
PubkeyAuthentication yes
AllowAgentForwarding no

# Additional hardening
KbdInteractiveAuthentication no
X11Forwarding no
AllowTcpForwarding no
PermitTunnel no
HostbasedAuthentication no
PermitEmptyPasswords no
StrictModes yes
AuthenticationMethods publickey
MaxAuthTries 3
LoginGraceTime 30
ClientAliveInterval 300
ClientAliveCountMax 2
LogLevel VERBOSE
