---
plugin: community.proxmox.proxmox

url: "{{ lookup('env', 'PROXMOX_ANSIBLE_PROXMOX_URL') }}"
user: "{{ lookup('env', 'PROXMOX_ANSIBLE_USER') }}"
token_id: "{{ lookup('env', 'PROXMOX_ANSIBLE_TOKEN_ID') }}"
token_secret: "{{ lookup('env', 'PROXMOX_ANSIBLE_TOKEN_SECRET') }}"
validate_certs: false

exclude_nodes: true

filters:
  - proxmox_vmtype == "qemu"
  - proxmox_status == "running"
  - "'managed_by_terraform' in (proxmox_tags | default('')).split(';')"
  - "'os_almalinux9' in (proxmox_tags | default('')).split(';')"
  - "'env_lab' in (proxmox_tags | default('')).split(';')"

groups:
    terraform_managed: "'managed_by_terraform' in (proxmox_tags | default('')).split(';')"
    almalinux9: "'os_almalinux9' in (proxmox_tags | default('')).split(';')"
    lab: "'env_lab' in (proxmox_tags | default('')).split(';')"