---
version: 3

images:
  base_image:
    name: registry.redhat.io/ubi9/ubi@sha256:151fc1b2c976f198779d740851436544fdf4e9449ccb4a47e2d0faad34f1733b

dependencies:
  ansible_core:
    package_pip: ansible-core==2.20.6
  ansible_runner:
    package_pip: ansible-runner==2.4.3
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
  python_interpreter:
    package_system: python3.12
    python_path: /usr/bin/python3.12

additional_build_files:
  - src: proxmox-pve-root-ca.crt
    dest: certs

additional_build_steps:
  append_final:
    - COPY _build/certs/proxmox-pve-root-ca.crt /etc/pki/ca-trust/source/anchors/proxmox-pve-root-ca.crt
    - RUN cat /etc/pki/ca-trust/source/anchors/proxmox-pve-root-ca.crt >> $(python3.12 -c "import certifi; print(certifi.where())")
    - RUN update-ca-trust