---
version: 3

images:
  base_image:
    name: ghcr.io/ansible-community/community-ee-minimal:2.20.6-1@sha256:ea7f2f7d853d4ab99f7c169e515dc5f836aa614bdb0c4ec83373a4f922f687e8

dependencies:
  galaxy: requirements.yml
  python: requirements.txt

additional_build_files:
  - src: proxmox-pve-root-ca.crt
    dest: certs

additional_build_steps:
  append_final:
    - COPY _build/certs/proxmox-pve-root-ca.crt /etc/pki/ca-trust/source/anchors/proxmox-pve-root-ca.crt
    - RUN update-ca-trust
    - ENV REQUESTS_CA_BUNDLE=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
